# Default initial positions for rm_eco65_gripper_description's ros2_control fake system

initial_positions:
  jaw_Joint1: 0
  jaw_Joint2: 0
  jaw_Joint3: 0
  jaw_Joint4: 0
  jaw_Joint5: 0
  jaw_Joint6: 0
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0